database:
  drive: mariadb
  url: localhost
  user: contas
  password: contas123
  name: contabilidade

allow_origins:
  - http://localhost:3000
  - http://localhost
  - http://localhost:8080

number:
  digits: 2